version: '3'
services:
  web:
    container_name: iluni-web
    image: php:7.4-apache
    ports:
      - "8081:80"
    volumes:
      - ./doc:/var/www/html
    networks:
      - vaf

networks:
    vaf:
      name: vaf